data:
  database:
    driver: "gorm-postgres"
    # Example: "host=localhost port=5432 user=postgres password=postgres dbname=postgres sslmode=disable"
    source: "host=POSTGRES_HOST port=5432 user=DB_USER password=DB_PASSWORD dbname=DB_NAME sslmode=disable"
    migrate: true
    debug: false
    enable_trace: false
    enable_metrics: false
    max_idle_connections: 25
    max_open_connections: 25
    connection_max_lifetime: 300s

  redis:
    addr: "localhost:6379"
    password: ""
    db: 0
    dial_timeout: 10s
    read_timeout: 0.4s
    write_timeout: 0.6s
    enable_tracing: false
    enable_metrics: false
